docker stop cim-app
docker stop cim-web
docker stop cim-nginx
docker stop cim-mysql
docker rm cim-app
docker rm cim-web
docker rm cim-nginx
docker rm cim-mysql
docker rmi copd-identify-manage-2_app
docker rmi copd-identify-manage-2_web
docker rmi copd-identify-manage-2_nginx
